core_themes:
  - structured_policy
  - cross_domain_synthesis
  - narrative_metaphors
  - mathematical_cycles
  - knowledge_visualization
  - essential_questions
  - temporal_coordination
  - pattern_recognition
  - neurodivergent_frameworks
  - field_coherence
  - boundary_architecture
  - sensory_intelligence
  - dimensional_translation

pattern_operators:
  - merge_separate
  - timing_misalignment
  - tension_release_distribution
  - boundary_coherence
  - recursive_collapse
  - field_interference
  - torus_flow
  - identity_knot
  - phase_sensitive_intervention
  - mirror_feedback
  - pattern_chunking

debugging_protocols:
  - overwhelm_debugging
  - decision_paralysis
  - temporal_misalignment
  - boundary_confusion
  - pattern_overload
  - sync_failure
  - coherence_breakdown
  - recursive_loops

applications:
  - bunny_os
  - macrosoma_integration
  - organizational_design
  - education_reform
  - consciousness_engineering
  - relationship_navigation