name: Python Compilation Check
on:
  push:
    paths: ["kb/**/*.py"]
  pull_request:
    paths: ["kb/**/*.py"]

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - name: Compile KB scripts
        run: |
          python -m py_compile $(git ls-files 'kb/**/*.py') 