name: Python Compilation Check

on:
  push:
    paths:
      - 'kb/**/*.py'
  pull_request:
    paths:
      - 'kb/**/*.py'

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Check Python compilation
        run: |
          cd kb
          python -m py_compile *.py
          echo "✅ All Python files compile successfully" 