name: Python Compilation Check
on:
  push:
    paths:
      - "kb/**/*.py"
      - ".github/workflows/python-check.yml"
  pull_request:
    paths:
      - "kb/**/*.py"

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Verify importability
        run: |
          python -m pip install --upgrade pip
          python -m py_compile $(git ls-files 'kb/**/*.py') 